---
- name: Reload Apache
  service:
    name: "apache2"
    state: reloaded

- name: Restart Apache
  service:
    name: "apache2"
    state: restarted

- name: Restart PHP-FPM
  service:
    name: "php7.4-fpm"
    state: restarted

- name: Restart Redis
  service:
    name: "redis-server"
    state: restarted