---
- name: Install libfontconfig1
  apt:
    pkg:
      - libfontconfig1
    state: present
    update_cache: yes

- name: Create folders
  file:  
    path: '{{ item }}'
    owner: root
    group: root
    mode: '0775'
    state: directory
    recurse: yes
  with_items:
    - /etc/prometheus
    - /etc/grafana

- name: Copy Prometheus Config
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: root
    mode: 0775

- name: start a prometheus container
  docker_container:
    name: prometheus
    image: prom/prometheus
    state: started
    restart: yes
    restart_policy: always
    interactive: true
    tty: yes
    ports:
     - "9090:9090"
    volumes: '{{ prometheus_volumes }}'

- name: Apply Grafana Conf
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
    owner: root
    group: root
    mode: 0775

- name: start a grafana container
  docker_container:
    name: grafana
    image: grafana/grafana-enterprise
    state: started
    restart: yes
    restart_policy: always
    interactive: true
    tty: yes
    ports:
     - "80:3000"
