---
- name: install PyMySQL
  pip: 
    name: PyMySQL
    state: latest

- name: Create Database 
  shell: mysql -e "CREATE DATABASE IF NOT EXISTS {{ db_name }};"

- name: Create User 
  shell: mysql -e "CREATE USER IF NOT EXISTS '{{ db_user }}'@'localhost' IDENTIFIED BY '{{ db_pw }}';"

- name: Permit User to Database
  shell: mysql -e "GRANT ALL ON {{ db_name }}.* TO '{{ db_user }}'@'localhost';"

#- name: Create Database
#  mysql_db:
#    name: "{{ db_name }}"
#    collation: utf8mb4_general_ci
#    encoding: utf8mb4
#    state: present
#    check_implicit_admin: yes
#
#- name: Create User
#  community.mysql.mysql_user:
#    name: "{{ db_user }}"
#    password: "{{ db_pw }}"
#    priv: '{{ db_name }}.*:ALL'
#    state: present
#    check_implicit_admin: yes
