---
- name: Check if let's encrypt cert exist
  become: true
  stat:
    path: /etc/letsencrypt/options-ssl-apache.conf
  register: stat_result

- name: start a onlyoffice container
  become: true
  docker_container:
    name: onlyoffice
    image: onlyoffice/documentserver
    state: started
    restart: yes
    restart_policy: always
    interactive: true
    tty: yes
    ports:
     - "{{ onlyoffice_ssl_port }}:443"
    env:
      ONLYOFFICE_HTTPS_HSTS_ENABLED: 'false'
      JWT_ENABLED:  'true'
      JWT_SECRET:   "{{ lookup('password', '{{ credential_store }}/onlyoffice_secret chars=ascii_letters,digits length=32') }}"
      USE_UNAUTHORIZED_STORAGE: 'true'
    volumes:        '{{ onlyoffice_volumes }}'
  when: stat_result.stat.exists

- name: start a onlyoffice container
  become: true
  docker_container:
    name: onlyoffice
    image: onlyoffice/documentserver
    state: started
    restart: yes
    restart_policy: always
    interactive: true
    tty: yes
    ports:
     - "{{ onlyoffice_ssl_port }}:443"
    env:
      ONLYOFFICE_HTTPS_HSTS_ENABLED: 'false'
      JWT_ENABLED:  'true'
      JWT_SECRET:   "{{ lookup('password', '{{ credential_store }}/onlyoffice_secret chars=ascii_letters,digits length=32') }}"
      USE_UNAUTHORIZED_STORAGE: 'true'
    volumes:        '{{ onlyoffice_volumes_local }}'
  when: not stat_result.stat.exists

- name: install onlyoffice app
  become: true
  become_user: www-data
  shell: php /var/www/nextcloud/occ app:install onlyoffice
  ignore_errors: true
  
- name: enable onlyoffice app
  become: true
  become_user: www-data
  shell: php /var/www/nextcloud/occ app:enable onlyoffice
  
- name: set onlyoffice server url
  become: true
  become_user: www-data
  shell: php /var/www/nextcloud/occ config:app:set onlyoffice DocumentServerUrl --value https://{{ external_url }}:{{ onlyoffice_ssl_port }}

- name: set onlyoffice server secret
  become: true
  become_user: www-data
  shell: php /var/www/nextcloud/occ config:app:set onlyoffice jwt_secret --value {{ lookup('password', '{{ credential_store }}/onlyoffice_secret chars=ascii_letters,digits length=32') }}

- name: set onlyoffice cert check off
  become: true
  become_user: www-data
  shell: php /var/www/nextcloud/occ config:system:set onlyoffice verify_peer_off --value=true --type=boolean

- name: certbot copy certificate
  become: true
  template:
    src: "onlyoffice.sh.j2"
    dest: "/etc/letsencrypt/renewal-hooks/post/onlyoffice.sh"